# Generated by Django 4.2.6 on 2023-11-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_picks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameselection',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
