# Generated by Django 4.2.23 on 2025-08-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(choices=[('NFL', 'National Football League'), ('NBA', 'National Basketball Association')], default='NFL', max_length=10)),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('status', models.CharField(default='scheduled', max_length=20)),
                ('winner', models.CharField(blank=True, max_length=100, null=True)),
                ('home_logo', models.URLField(blank=True, null=True)),
                ('away_logo', models.URLField(blank=True, null=True)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('game_week', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'ordering': ['start_time'],
            },
        ),
    ]
