# Generated by Django 4.2.23 on 2025-09-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('regular', 'Regular Season'), ('playoff', 'Playoff'), ('superbowl', 'Super Bowl'), ('wildcard', 'Wild Card'), ('divisional', 'Divisional'), ('conference', 'Conference Championship')], default='regular', max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('final', 'Final'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
    ]
