# Generated by Django 4.2.23 on 2025-08-24 01:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_game_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 8, 24, 1, 22, 59, 953364, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.CharField(blank=True, help_text='REG, WC, DIV, CON, SB', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='season',
            field=models.IntegerField(blank=True, help_text='NFL season year', null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('external_id',), name='unique_external_id_when_not_null'),
        ),
    ]
