# Generated by Django 4.2.23 on 2026-06-26 02:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0003_fix_game_times_to_utc"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="spread",
            field=models.FloatField(
                blank=True,
                help_text="Point spread (negative = home favored)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="spread_favorite",
            field=models.CharField(
                blank=True,
                choices=[("home", "Home"), ("away", "Away")],
                max_length=10,
                null=True,
            ),
        ),
    ]
