# Generated by Django 4.2.23 on 2025-09-14 03:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="password_reset_sent",
            field=models.BooleanField(default=False),
        ),
    ]
