# Generated by Django 4.2.23 on 2026-06-26 02:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_profile_password_reset_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="cpu_challenge_active",
            field=models.BooleanField(default=False),
        ),
    ]
