# Generated by Django 4.2.23 on 2026-09-04 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("games", "0004_add_spread_fields"),
        ("users", "0004_add_notifications_and_reminders"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reminderlog",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="reminderlog",
            name="game",
            field=models.ForeignKey(
                blank=True,
                help_text="The specific game this reminder was for (null for weekly).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reminder_logs",
                to="games.game",
            ),
        ),
        migrations.AlterField(
            model_name="reminderlog",
            name="reminder_type",
            field=models.CharField(
                choices=[
                    ("weekly", "Weekly Slate"),
                    ("day_before", "Day Before"),
                    ("morning_of", "Morning Of"),
                    ("hours_before", "Hours Before Kickoff"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="reminderlog",
            unique_together={("user", "reminder_type", "week", "season", "game")},
        ),
    ]
