# Generated by Django 4.2.23 on 2026-09-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_reminderlog_unique_together_reminderlog_game_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reminderlog",
            name="reminder_type",
            field=models.CharField(
                choices=[
                    ("weekly", "Weekly Slate"),
                    ("day_before", "Day Before"),
                    ("morning_of", "Morning Of"),
                    ("hours_before", "Hours Before Kickoff"),
                    ("recap", "Weekly Recap"),
                ],
                max_length=20,
            ),
        ),
    ]
