# Generated by Django 4.2.23 on 2025-09-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='league',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='leaguecreationrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='leaguejoinrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='league',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaguecreationrequest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
