# Generated by Django 4.2.23 on 2026-06-26 02:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0002_add_description_and_fix_defaults"),
    ]

    operations = [
        migrations.AlterField(
            model_name="league",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
    ]
