# Generated by Django 4.2.23 on 2025-09-02 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('picks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_picks', models.IntegerField(default=0)),
                ('correct_picks', models.IntegerField(default=0)),
                ('win_percentage', models.FloatField(default=0.0)),
                ('total_points', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'League Stats',
                'verbose_name_plural': 'League Stats',
            },
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_picks', models.IntegerField(default=0)),
                ('correct_picks', models.IntegerField(default=0)),
                ('win_percentage', models.FloatField(default=0.0)),
                ('current_streak', models.IntegerField(default=0)),
                ('best_streak', models.IntegerField(default=0)),
                ('primetime_picks', models.IntegerField(default=0)),
                ('primetime_correct', models.IntegerField(default=0)),
                ('primetime_win_percentage', models.FloatField(default=0.0)),
                ('total_points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Stats',
                'verbose_name_plural': 'User Stats',
            },
        ),
        migrations.AlterField(
            model_name='pick',
            name='is_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pick',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leagues.league'),
        ),
        migrations.AddIndex(
            model_name='pick',
            index=models.Index(fields=['user', 'created_at'], name='picks_pick_user_id_9e41ee_idx'),
        ),
        migrations.AddIndex(
            model_name='pick',
            index=models.Index(fields=['game', 'is_correct'], name='picks_pick_game_id_556c4e_idx'),
        ),
        migrations.AddIndex(
            model_name='pick',
            index=models.Index(fields=['league', 'created_at'], name='picks_pick_league__ce9fd5_idx'),
        ),
        migrations.AddField(
            model_name='userstats',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pick_stats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaguestats',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.league'),
        ),
        migrations.AddField(
            model_name='leaguestats',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userstats',
            index=models.Index(fields=['win_percentage'], name='picks_users_win_per_5ff813_idx'),
        ),
        migrations.AddIndex(
            model_name='userstats',
            index=models.Index(fields=['total_points'], name='picks_users_total_p_75518e_idx'),
        ),
        migrations.AddIndex(
            model_name='userstats',
            index=models.Index(fields=['best_streak'], name='picks_users_best_st_7f3fec_idx'),
        ),
        migrations.AddIndex(
            model_name='leaguestats',
            index=models.Index(fields=['league', 'win_percentage'], name='picks_leagu_league__5e145f_idx'),
        ),
        migrations.AddIndex(
            model_name='leaguestats',
            index=models.Index(fields=['league', 'total_points'], name='picks_leagu_league__35b0bb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leaguestats',
            unique_together={('user', 'league')},
        ),
    ]
