# Generated by Django 4.2.23 on 2025-09-09 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0002_leaguestats_userstats_alter_pick_is_correct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pick',
            name='confidence',
            field=models.IntegerField(default=1),
        ),
    ]
