# Generated by Django 4.2.23 on 2026-06-26 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0004_add_spread_fields"),
        ("picks", "0003_add_confidence_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="CPUPick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("picked_team", models.CharField(max_length=50)),
                ("is_correct", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cpu_pick",
                        to="games.game",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_correct"], name="picks_cpupi_is_corr_a2c1c5_idx"
                    )
                ],
            },
        ),
    ]
