# Generated by Django 4.2.23 on 2026-06-26 22:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("picks", "0004_add_cpupick_model"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="pick",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="pick",
            constraint=models.UniqueConstraint(
                condition=models.Q(("league__isnull", False)),
                fields=("user", "game", "league"),
                name="unique_pick_with_league",
            ),
        ),
        migrations.AddConstraint(
            model_name="pick",
            constraint=models.UniqueConstraint(
                condition=models.Q(("league__isnull", True)),
                fields=("user", "game"),
                name="unique_pick_without_league",
            ),
        ),
    ]
