# Generated by Django 4.2.6 on 2023-11-20 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nflgame',
            name='date',
            field=models.DateField(default='2023-11-11'),
            preserve_default=False,
        ),
    ]
