# Generated by Django 4.2.6 on 2023-11-20 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_schedule', '0002_nflgame_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nflgame',
            name='date',
            field=models.DateField(default='111/11/11'),
        ),
    ]
